#!/bin/sh
set -e

action="$1"
umask 022

. /usr/share/debconf/confmodule

setup_mlvpn_user() {
    if ! getent passwd mlvpn >/dev/null; then
        adduser --quiet --system --no-create-home --home /run/mlvpn --shell /usr/sbin/nologin mlvpn
    fi
}

case "$action" in
  configure)
    db_get mlvpn/create_tun || RET="false"
    if [ "$RET" = "true" ]; then
      [ -e /dev/net ] || mkdir -m 755 /dev/net
      [ -d /dev/net -a ! -e /dev/net/tun ] && mknod /dev/net/tun c 10 200
    fi
    setup_mlvpn_user
  ;;
esac

db_stop

#DEBHELPER#
exit 0
